name: "Debian proot-distro rootfs with gemini cli (containerized)"

on:
  schedule:
# Build Every Months
    - cron: "0 0 1 * *"
  workflow_dispatch:

permissions:
  contents: write  

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Install Needed Dependencies
        run: |
          sudo apt update && sudo apt install -yq curl xz-utils
          curl -L -o /tmp/mmdebstrap.deb http://ftp.us.debian.org/debian/pool/main/m/mmdebstrap/mmdebstrap_1.5.7-3_all.deb
          sudo apt install -yq /tmp/mmdebstrap.deb
          curl -L -o /tmp/keyring.deb http://ftp.us.debian.org/debian/pool/main/d/debian-archive-keyring/debian-archive-keyring_2025.1_all.deb
          sudo apt install -yq /tmp/keyring.deb
      - name: Start Building
        run: |
          curl -L -o debian-stable-aarch64.tar.xz https://github.com/arfshl/pd-custom-rootfs/releases/download/debian-stable/debian-stable-aarch64.tar.xz
          tar --exclude=dev/* -xJf debian-stable-aarch64.tar.xz
          sudo mkdir -p $GITHUB_WORKSPACE/debian/dev
          sudo mkdir -p $GITHUB_WORKSPACE/debian/proc
          sudo mkdir -p $GITHUB_WORKSPACE/debian/sys
          sudo mkdir -p $GITHUB_WORKSPACE/debian/tmp
          sudo chmod -R 755 $GITHUB_WORKSPACE/debian
          sudo chmod -R 1777 $GITHUB_WORKSPACE/debian/tmp
          sudo mount --bind /dev $GITHUB_WORKSPACE/debian/dev
          sudo mount --bind /proc $GITHUB_WORKSPACE/debian/proc
          sudo mount --bind /sys $GITHUB_WORKSPACE/debian/sys
          sudo chroot $GITHUB_WORKSPACE/debian /bin/sh -c "apt update && apt upgrade -yq && apt install curl wget nano build-essential -yq && curl -L -o setupnode https://deb.nodesource.com/setup_24.x && chmod +x setupnode && ./setupnode && apt install nodejs -y && npm install -g yarn && yarn global add @google/gemini-cli"
          sudo umount -l $GITHUB_WORKSPACE/debian/dev
          sudo umount -l $GITHUB_WORKSPACE/debian/proc
          sudo umount -l $GITHUB_WORKSPACE/debian/sys
          sudo tar --exclude=dev/* -cf - ./ | xz -9 -T0 -c > gemini-cli-debian-stable.tar.xz
          
      - name: Push to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: Debian proot-distro rootfs with gemini cli (containerized) (ARM64)
          files: |
            gemini-cli-debian-stable.tar.xz
          preserve_order: true
          make_latest: true
